GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/5

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstname": "Marco",
  "lastname": "Pollo"
}

###

DELETE http://localhost:3000/api/users/1

###

PATCH  http://localhost:3000/api/users/5
Content-Type: application/json

{
  "firstname": "Marco",
  "lastname": "Pollo 2"
}

###

PATCH http://localhost:3000/api/users/5/toggle